chat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # path('', TemplateView.as_view(template_name="chat/index.html")),
    path("", views.role_playing_room_list, name="role_playing_room_list"),  # 🔥 HERE
    path('new/', views.role_playing_room_new, name="role_playing_room_new"),
    path("<int:pk>/", views.role_playing_room_detail, name="role_playing_room_detail"),
    path("<int:pk>/edit/", views.role_playing_room_edit, name="role_playing_room_edit"),
    path("<int:pk>/delete/", views.role_playing_room_delete, name="role_playing_room_delete"),  # 🔥 HERE
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('', RedirectView.as_view(url='/chat/')),
]

chat/models.py
# chat/models.py

from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models

from django.urls import reverse
from typing import TypedDict, Literal, List

class GptMessage(TypedDict):
    role: Literal["system", "user", "assistant"]
    content: str


class RolePlayingRoom(models.Model):
    class Language(models.TextChoices):
        ENGLISH = "en-US", "English"
        JAPANESE = "ja-JP", "Japanese"
        CHINESE = "zh-CN", "Chinese"
        SPANISH = "es-ES", "Spanish"
        FRENCH = "fr-FR", "French"
        GERMAN = "de-DE", "German"
        RUSSIAN = "ru-RU", "Russian"
    

    class Level(models.IntegerChoices):
        BEGINNER = 1, "초급"
        ADVANCED = 2, "고급"

    class Meta:
        ordering = ["-pk"]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    language = models.CharField(
        max_length=10, choices=Language.choices, default=Language.ENGLISH,
        verbose_name="대화 언어")
    level = models.SmallIntegerField(
        choices=Level.choices, default=Level.BEGINNER, verbose_name="레벨")

    situation = models.CharField(
        max_length=100,
        validators=[MinLengthValidator(3)], verbose_name="상황")
    situation_en = models.CharField(
        max_length=100, blank=True, verbose_name="상황 (영문)",
        help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, 자동으로 번역됩니다.")
    my_role = models.CharField(max_length=100, verbose_name="내 역할")
    my_role_en = models.CharField(
        max_length=100, blank=True, verbose_name="내 역할 (영문)",
        help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, 자동으로 번역됩니다.")
    gpt_role = models.CharField(max_length=100, verbose_name="GPT 역할")
    gpt_role_en = models.CharField(
        max_length=100, blank=True, verbose_name="GPT 역할 (영문)",
        help_text="GPT 프롬프트에 직접적으로 활용됩니다. 비워두시면, 자동으로 번역됩니다.")
    

    def get_absolute_url(self) -> str:
        return reverse("role_playing_room_detail", args=[self.pk])
    
    def get_initial_messages(self) -> List[GptMessage]:
        gpt_name = "RolePlayingBot"
        language = self.get_language_display()
        situation_en = self.situation_en
        my_role_en = self.my_role_en
        gpt_role_en = self.gpt_role_en

        if self.level == self.Level.BEGINNER:
            level_string = f"a beginner in {language}"
            level_word = "simple"
        elif self.level == self.Level.ADVANCED:
            level_string = f"an advanced learner in {language}"
            level_word = "advanced"
        else:
            raise ValueError(f"Invalid level : {self.level}")
        
        system_message = (
            f"You are helpful assistant supporting people learning {language}. "
            f"Your name is {gpt_name}. "
            f"Please assume that the user you are assisting is {level_string}. "
            f"And please write only the sentence without the character role."
        )
        
        user_message = (
            f"Let's have a conversation in {language}. "
            f"Please answer in {language} only "
            f"without providing a translation. "
            f"And please don't write down the pronunciation either. "
            f"Let us assume that the situation in '{situation_en}'. "
            f"I am {my_role_en}. The character I want you to act as is {gpt_role_en}. "
            f"Please make sure that I'm {level_string}, so please use {level_word} words "
            f"as much as possible. Now, start a conversation with the first sentence!"
        )
        
        return [
            GptMessage(role="system", content=system_message),
            GptMessage(role="user", content=user_message),
        ]

chat/forms.py
# chat/forms.py

from django import forms
from .models import RolePlayingRoom
from .translators import google_translate


class RolePlayingRoomForm(forms.ModelForm):
    class Meta:
        model = RolePlayingRoom
        fields = [
            "language",
            "level",
            "situation",
            "situation_en",
            "my_role",
            "my_role_en",
            "gpt_role",
            "gpt_role_en",
        ]

    def clean(self):
        situation = self.cleaned_data.get("situation")
        situation_en = self.cleaned_data.get("situation_en")
        if situation and not situation_en:
            self.cleaned_data["situation_en"] = self._translate(situation)

        my_role = self.cleaned_data.get("my_role")
        my_role_en = self.cleaned_data.get("my_role_en")
        if my_role and not my_role_en:
            self.cleaned_data["my_role_en"] = self._translate(my_role)

        gpt_role = self.cleaned_data.get("gpt_role")
        gpt_role_en = self.cleaned_data.get("gpt_role_en")
        if gpt_role and not gpt_role_en:
            self.cleaned_data["gpt_role_en"] = self._translate(gpt_role)

    @staticmethod
    def _translate(origin_text: str) -> str:
        translated = google_translate(origin_text, "auto", "en")
        if not translated:
            raise forms.ValidationError("구글 번역을 할 수 없습니다.")
        return translated

chat/views.py
# chat/views.py

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.views.generic import CreateView

from chat.forms import RolePlayingRoomForm
from chat.models import RolePlayingRoom
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView

# 아직 로그인 기능을 구현하지 않았기에, admin 앱의 로그인 기능을 활용토록 합니다.
@method_decorator(staff_member_required, name="dispatch")
class RolePlayingRoomCreateView(CreateView):
    model = RolePlayingRoom
    form_class = RolePlayingRoomForm
    # success_url = reverse_lazy("role_playing_room_new")  # 페이지 성공 후에 이동할 페이지 주소 지정

    def form_valid(self, form):
        role_playing_room = form.save(commit=False)
        role_playing_room.user = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "새로운 채팅방을 생성했습니다.")
        return response


role_playing_room_new = RolePlayingRoomCreateView.as_view()

@method_decorator(staff_member_required, name="dispatch")
class RolePlayingRoomUpdateView(UpdateView):
    model = RolePlayingRoom
    form_class = RolePlayingRoomForm
    # success_url = reverse_lazy("role_playing_room_new")

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "채팅방을 수정했습니다.")
        return response


role_playing_room_edit = RolePlayingRoomUpdateView.as_view()


@method_decorator(staff_member_required, name="dispatch")
class RolePlayingRoomListView(ListView):
    model = RolePlayingRoom

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


role_playing_room_list = RolePlayingRoomListView.as_view()


@method_decorator(staff_member_required, name="dispatch")
class RolePlayingRoomDetailView(DetailView):
    model = RolePlayingRoom

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


role_playing_room_detail = RolePlayingRoomDetailView.as_view()

@method_decorator(staff_member_required, name="dispatch")
class RolePlayingRoomDeleteView(DeleteView):
    model = RolePlayingRoom
    success_url = reverse_lazy("role_playing_room_list")

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "채팅방을 삭제했습니다.")
        return response


role_playing_room_delete = RolePlayingRoomDeleteView.as_view()

chat/templates/chat/base.html
{# chat/templates/chat/base.html #}

{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>장고 채널스와 함께 ChatGPT 영어 상황극 채팅 서비스 만들기</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% block extra-css %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
                <a href="/"
                   class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                    <span class="fs-4">장고 채널스와 함께 ChatGPT 영어 상황극 채팅 서비스 만들기</span>
                </a>

                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a href="/chat/new" class="nav-link active">새 상황 만들기</a>
                    </li>
                </ul>
            </header>
        </div>
        <div class="container">
            {% bootstrap_messages %}

            {% block content %}{% endblock %}

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <small class="d-block mb-3 text-muted">&copy; 2023. 파이썬 사랑방</small>
                    </div>
                </div>
            </footer>

            {% block script %}{% endblock %}
        </div>
    </body>
</html>

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block content %}
    HELLO WORLD
{% endblock %}

chat/templates/chat/roleplayingroom_confirm_delete.html
{% extends "chat/base.html" %}

{% block content %}
    <h2>채팅방 삭제하기</h2>

    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-warning">
            &lt;{{ object.situation }}&gt; 채팅방을 정말 삭제하시겠습니까?
        </div>
        <input type="submit" value="삭제하겠습니다." class="btn btn-danger" />
    </form>
{% endblock %}

chat/templates/chat/roleplayingroom_detail.html
{% extends "chat/base.html" %}

{% block extra-css %}
<style>
    #chat-message-list {
        padding: 0;
        list-style: none;
    }
    .chat-message .message {
        background-color: #3b3b3d;
        color: #e1e1e1;
        border-radius: 0.8em;
        padding: 0.4em;
        margin: 0.4em 0;
        display: inline-block;
        white-space: pre-wrap;
    }

    .chat-message.me {
        text-align: right;
    }
    .chat-message.me .message {
        background-color: #1f8cff;
        color: #fff;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    [{{ roleplayingroom.get_language_display }}
                    {{ roleplayingroom.get_level_display }}]
                    {{ roleplayingroom.situation }}
                    ({{ roleplayingroom.gpt_role }}와 {{ roleplayingroom.my_role }}의 대화)
                </div>
                <div class="card-body">
                    <ul id="chat-message-list">

                    </ul>
                </div>
                <div class="card-footer">
                    <div class="d-flex gap-2">
                        <form id="message-form" class="d-flex gap-1 flex-grow-1">
                            <input type="text"
                                   name="message"
                                   placeholder="메시지를 입력하세요."
                                   class="form-control flex-grow-1" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="my-3">
        <a href="{% url 'role_playing_room_edit' roleplayingroom.pk %}"
           class="btn btn-primary">수정</a>
        {# 🔥 HERE #}
        <a href="{% url 'role_playing_room_delete' roleplayingroom.pk %}"
           class="btn btn-danger">삭제</a>
    </div>
{% endblock %}



{% block script %}
{{ roleplayingroom.pk|json_script:"room-pk" }}

<script>
(function() {
    const room_pk = document.querySelector("#room-pk").textContent;
    const ws = new WebSocket(`ws://${window.location.host}/ws/chat/${room_pk}/`);

    ws.onopen = function(e) { console.log("장고 채널스 서버와 웹소켓 연결되었습니다."); };
    ws.onclose = function(e) { console.log('장고 채널스 서버와 웹소켓 연결이 끊어졌습니다.'); };
    ws.onerror = function(e) { console.error("장고 채널스 서버와의 웹소켓 연결 중에 오류가 발생했습니다.", e); };
    // 서버로부터 웹소켓 메시지를 받았을 때 호출되는 함수.

    ws.onmessage = function(e) {
        console.group("[onmessage]");
        // console.log(typeof e.data);
        // console.log(e.data);
        // 🔥 HERE
        const message_obj = JSON.parse(e.data);

        if ( message_obj.type === "assistant-message" ) {
            const { message } = message_obj;
            console.log("assistant-message:", message);
            addMessage(message, false);  // 🔥 추가됨
        }
    
        else if ( message_obj.type === "openai-error" ) {
            const { message } = message_obj;
            alert(`Error: ${message}`);
        }
        else {
            console.error("알 수 없는 메시지 타입입니다.", message_obj);
        }
    
        console.groupEnd();
    };

    const messageForm = document.getElementById("message-form");
    messageForm.onsubmit = function(e) {
        e.preventDefault();
        const message = e.target.message.value.trim();
        if(message.length > 0) {
            addMessage(message, true);  // ⭐️ 추가
            ws.send(JSON.stringify({ type: "user-message", message: message }));  // ⭐️ type 추가
            e.target.reset();
        }
    };
    
})();



function addMessage(message, isMe) {
    const messageList = document.getElementById("chat-message-list");
    const messageElement = document.createElement("li");
    messageElement.className = "chat-message" + (isMe ? " me" : "");
    messageElement.innerHTML = `<span class="message">${message}</span>`;
    messageList.appendChild(messageElement);
    messageList.scrollTop = messageList.scrollHeight;
}


</script>

{% endblock %}

chat/templates/chat/roleplayingroom_form.html
{% extends "chat/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
    <div class="card border-dark">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            <div class="card-header">
                {# 🔥 HERE !!! #}
                상황 {% if form.instance.pk %}수정하기{% else %}만들기{% endif %}
            </div>
            <div class="card-body">{% bootstrap_form form layout="horizontal" %}</div>
            <div class="card-footer text-end">
                <input type="submit" value="저장하기" class="btn btn-primary" />
            </div>
        </form>
    </div>
{% endblock %}

chat/templates/chat/roleplayingroom_list.html
{% extends "chat/base.html" %}

{% block content %}
<table class="table table-hover table-bordered">
    <thead>
        <tr class="text-center">
            <th>언어</th>
            <th>레벨</th>
            <th>상황</th>
            <th>내 역할</th>
            <th>GPT 역할</th>
        </tr>
    </thead>
    <tbody>
        {% for role_playing_room in object_list %}
            <tr>
                <td>{{ role_playing_room.get_language_display }}</td>
                <td>{{ role_playing_room.get_level_display }}</td>
                <td>
                    <a href="{{ role_playing_room.get_absolute_url }}">{{ role_playing_room.situation }}</a><br />
                    <small>({{ role_playing_room.situation_en }})</small>
                </td>
                <td>
                    {{ role_playing_room.my_role }}<br />
                    <small>({{ role_playing_room.my_role_en }})</small>
                </td>
                <td>
                    {{ role_playing_room.gpt_role }}<br />
                    <small>({{ role_playing_room.gpt_role_en }})</small>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">Empty</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}